---
development:
  dialect: mysql
  database: coke_dev
  user: root
  password: root
  host: 172.24.0.1
  pool: 5

test:
  dialect: mysql
  database: coke_test
  user: root
  password: root
  host: 172.24.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/coke_production?sslmode=disable"}}
